FROM amazonlinux:latest

RUN yum update -y && \
    yum install -y httpd openssh-server sudo && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN useradd -m -s /bin/bash docker && \
    echo 'docker:password' | chpasswd && \
    usermod -aG wheel docker

RUN sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/^ChallengeResponseAuthentication.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config && \
    sed -i 's/^#PermitRootLogin.*$/PermitRootLogin no/' /etc/ssh/sshd_config && \
    sed -i 's/^#UseDNS.*$/UseDNS no/' /etc/ssh/sshd_config && \
    sed -i 's/^#UsePAM.*$/UsePAM yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#SyslogFacility.*$/SyslogFacility AUTH/' /etc/ssh/sshd_config && \
    sed -i 's/^#LogLevel.*$/LogLevel INFO/' /etc/ssh/sshd_config && \
    mkdir /var/run/sshd

EXPOSE 22 80

# Install Supervisor
RUN yum install -y python3-pip && \
    pip3 install --upgrade pip && \
    pip3 install supervisor && \
    mkdir -p /var/log/supervisor

# Configure Supervisor
COPY supervisord.conf /etc/supervisord.conf

CMD ["/usr/bin/supervisord"]
