# Base image
FROM amazonlinux:latest

# Install necessary packages
RUN yum update -y && \
    yum install -y openssh-server sudo && \
    yum clean all && \
    rm -rf /var/cache/yum

# Create user and set password
RUN useradd -m -s /bin/bash docker && \
    echo 'docker:password' | chpasswd && \
    usermod -aG wheel docker

# SSH Configuration
RUN sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/^ChallengeResponseAuthentication.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config && \
    sed -i 's/^#PermitRootLogin.*$/PermitRootLogin no/' /etc/ssh/sshd_config && \
    sed -i 's/^#UseDNS.*$/UseDNS no/' /etc/ssh/sshd_config && \
    sed -i 's/^#UsePAM.*$/UsePAM yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#SyslogFacility.*$/SyslogFacility AUTH/' /etc/ssh/sshd_config && \
    sed -i 's/^#LogLevel.*$/LogLevel INFO/' /etc/ssh/sshd_config && \
    mkdir /var/run/sshd

# Expose SSH port
EXPOSE 22

# Start SSH service
CMD ["/usr/sbin/sshd", "-D"]
